### PR TITLE
added show instances for multiple janno column types

### PR DESCRIPTION
**Pull request by nevrome**
This is related to #72: To display the janno columns "correctly" (i.e. as in the janno files) in `list --individuals`, we need the right Show instance definitions (or something comparable). The JSON encoding is not relevant for that, although still a valid issue by itself.

This PR has some Show instances for our janno column types to make sure that the output of `list` and the representation in the janno files are identical. An issue arises for `Sex`, as it and its Show instance are defined in SequenceFormats.Eigenstrat and can not be overwritten here.

I assume a "clean" solution would be to switch to an own typeclass for janno-like printing (e.g. `JannoShow`), but that would mean going through the user facing code and replacing `show` with `jannoShow` wherever necessary.

### CODE REVIEW

**Review by stschiff — APPROVED** [review]
Looks great, thank you! I'll merge this because I'm preparing another PR.

**Comment by stschiff** [comment]
Oops. Merge conflict. Can you take care of this, @nevrome?

**Comment by nevrome** [comment]
Hm - the `sex` issue is not solved with this PR, unfortunately. But I will just open an issue for that.

**Comment by nevrome** [comment]
Can be merged now

**Comment by stschiff** [comment]
Great, waiting for the CI to finish, then I'll merge.

**Comment by nevrome** [comment]
That will take more than an hour :shrug:

**Comment by stschiff** [comment]
Oof. OK, will merge now.

**Pull request merged**
