### PR TITLE
Allow custom SNP file in forge

### PR DESCRIPTION
**Pull request by stschiff**
I've started implementing the feature requested in #131.

### CODE REVIEW

**Comment by nevrome** [comment]
Excellent! I'll run a test in a minute, but I'm sure it does what it is supposed to. Maybe @bvernot is interested in giving it a try as well. He was asking for the feature in #131, after all.

***

- The `LambdaCase` extension is cool! How do you discover these? I'm always overwhelmed when I look at the list of extensions I *could* use.
- I don't understand why the change to `test/testDat/testModules/ancient/Schiffels_2016` was necessary. You just removed an arbitrary snp from this small test package, right? This has the consequence that a dozen of derived files in the Golden test setup change as well. That's fine in general, but why? What do we win by changing all these files?

**Comment by nevrome** [comment]
My test was successful. Brilliant! I got an irritating error message first, because my snp file for `--selectSnps` had a trailing linebreak. I guess that is a general issue when reading .snp files. Could `SequenceFormats.Eigenstrat` be taught to ignore empty lines? Or would that be harmful in an unexpected way? Should I open an issue [here](https://github.com/stschiff/sequence-formats)?

**Comment by stschiff** [comment]
I will add one more check that the input SNP file is sorted, then prepare to merge.

**Comment by bvernot** [comment]
This is great, thank you! I will put it through the paces soon.

**Comment by stschiff** [comment]
OK, I've added one more test and check that the custom SNP file is ordered. If the CI testing goes through I'll merge this.

**Pull request merged**
