### PR TITLE
More general update module

### PR DESCRIPTION
**Pull request by nevrome**
First, fully untested draft to cover #110. I'll finish it asap

### CODE REVIEW

**Comment by nevrome** [comment]
Here's the interface I came up with:

```
Usage: trident update (-d|--baseDir DIR) [--poseidonVersion ARG] 
                      [--versionComponent ARG] [--noChecksumUpdate] 
                      [--newContributors ARG] [--logText ARG] [--force]
  Update POSEIDON.yml files automatically

Available options:
  -h,--help                Show this help text
  -d,--baseDir DIR         a base directory to search for Poseidon Packages
                           (could be a Poseidon repository)
  --poseidonVersion ARG    Poseidon version the packages should be updated to:
                           e.g. "2.5.3" (default: Nothing)
  --versionComponent ARG   Part of the package version number in the
                           POSEIDON.yml file that should be updated: Major,
                           Minor or Patch (see
                           https://semver.org) (default: Patch)
  --noChecksumUpdate       Should update of checksums in the POSEIDON.yml file
                           be skipped
  --ignoreGeno             ignore SNP and GenoFile
  --newContributors ARG    Contributors to add to the POSEIDON.yml file in the
                           form "[Firstname Lastname](Email address);..."
  --logText ARG            Log text for this version jump in the CHANGELOG
                           file (default: "not specified")
  --force                  Normally the POSEIDON.yml files are only changed if
                           the poseidonVersion is adjusted or any of the
                           checksums change. With --force a package version
                           update can be triggered even if this is not the case.
```

Note the `--force` option to press an update even if no checksums changed.

One example: If I would like to add myself as a contributor for all packages I could run the following command

```bash
trident update -d . --newContributors "[Clemens Schmid](schmid@shh.mpg.de)" --logText "Added Clemens as a contributor" --force
```

This will modify the POSEIDON.yml files to 

- add the new contributor
- increment the package version number by one in the patch field
- update the lastModified field
- add `changelogFile: CHANGELOG.md` (if there was no CHANGELOG file before)

And it will create/modify the CHANGELOG file with the following line:

```
V X.X.X: Added Clemens as a contributor
```

where `X.X.X` is the respective new version number of the package

I did not write unit and golden tests yet, but I think you could try it anyway, @stschiff

**Comment by stschiff** [comment]
Very nice. I haven't reviewed the code in detail, but I think I'm OK with merging this PR if the command works. Definitely very nice interface!

**Comment by nevrome** [comment]
I feel bad about saying this, because I know that you/we have a lot of other things to do as well, but maybe you could at least run some test cases to check if things behave as expected. 

I also didn't write any tests yet. `update` might be a solution to fix the issue in #107 :thinking:

**Comment by stschiff** [comment]
OK, will take a look. 

> update might be a solution to fix the issue in #107 🤔

How so?

**Pull request merged**
