### PR TITLE
Optimize genotype merging

### PR DESCRIPTION
**Pull request by stschiff**
starting to work on genotype merging optimisation.

### CODE REVIEW

**Comment by stschiff** [comment]
I have implemented a new algorithm to merge genotypes, which is much faster and has the same safety as before. I have also implemented a new option `--no-extract` which disables the selection step after the package merge, and which results in around 50% speed up in cases where entire packages are merged anyway.

I've made extensive performance tests. Here are the results:

# Forge performance experiments

We always kill the job after 100,000 SNPs, and I've selected 8 packages or individuals therein to be forged:

## this branch:

Forging Full packages:
16.98s user 0.29s system 98% cpu 17.475 total

Forging Full packages with --no-extract
11.99s user 0.21s system 99% cpu 12.246 total

Forging half the individuals in these packages:
12.98s user 0.19s system 96% cpu 13.630 total

Forging half the individuals with --no-extract:
12.73s user 0.25s system 99% cpu 13.086 total

One individual from each package:
8.90s user 0.14s system 99% cpu 9.085 total

One individual from each package with --no-extract
11.94s user 0.21s system 99% cpu 12.248 total

## branch: master
Full packages:
83.99s user 0.84s system 98% cpu 1:25.73 total

Half the individuals:
77.26s user 0.71s system 99% cpu 1:18.40 total

One individual from each package:
74.16s user 0.64s system 99% cpu 1:15.49 total

## branch: forge_performance_experiments
Full packages:
23.50s user 0.30s system 98% cpu 24.232 total

Half the individuals:
emits error...

One individual from each package:
12.07s user 0.16s system 99% cpu 12.293 total


# Conclusion:
The new branch is faster than master in all cases, and close to Clemens' error hack in branch forge_performance_experiments. The new option `--no-extract` makes a difference when entire packages are merged, but makes things slower when only few individuals are extracted. That is expected, since then the overhead of writing much larger files is bigger than the time-save in the selection step.

**Comment by nevrome** [comment]
I ran the following tests on the current state of published_data with the old and new trident versions and compared the relevant result file checksums for `.bed`, `.bib`, `.bim`, `.fam` and `.janno` manually:

```
trident forge -d . -f "<COD147>,<COV20126.SG>,<I13980>,<s19_X10_1.SG>,<A_Yoruba-4.DG>" -o ~/test/forgetest/st_extract_union -n st_extract_union
trident forge -d . -f "<COD147>,<COV20126.SG>,<I13980>,<s19_X10_1.SG>,<A_Yoruba-4.DG>" -o ~/test/forgetest/st_extract_intersect -n st_extract_intersect --intersect
trident forge -d . -f "*2019_Nikitin_LBK*,*2020_TeschlerNicola_UpperPaleoTwin*,*2020_Lipson_WestAfrica*,*2014_OlaldeNature*" -o ~/test/forgetest/st_pac_extract -n st_pac_extract
trident forge -d . -f "*2019_Nikitin_LBK*,*2020_TeschlerNicola_UpperPaleoTwin*,*2020_Lipson_WestAfrica*,*2014_OlaldeNature*" -o ~/test/forgetest/st_pac_noextract -n st_noextract --no-extract
***
trident forge -d . -f "<COD147>,<COV20126.SG>,<I13980>,<s19_X10_1.SG>,<A_Yoruba-4.DG>" -o ~/test/forgetest/old_extract_union -n old_extract_union
trident forge -d . -f "<COD147>,<COV20126.SG>,<I13980>,<s19_X10_1.SG>,<A_Yoruba-4.DG>" -o ~/test/forgetest/old_extract_intersect -n old_extract_intersect --intersect
trident forge -d . -f "*2019_Nikitin_LBK*,*2020_TeschlerNicola_UpperPaleoTwin*,*2020_Lipson_WestAfrica*,*2014_OlaldeNature*" -o ~/test/forgetest/old_pac_extract -n old_pac_extract
```
In this test I did not observe any differences, which confirms that this much faster reimplementation yields results of the same quality as the established code. Excellent!

**Review by nevrome — APPROVED** [review]
I think it's all brilliant and can be merged :+1:

**Comment by stschiff** [comment]
Perfect. Thanks!

**Pull request merged**
