### PR TITLE
Better parsing exceptions

### PR DESCRIPTION
**Pull request by nevrome**
There are some trident error messages that are not well rendered on the command line. This PR is an attempt to improve them. Here's some examples of what I did so far:

***
`-f "<<>"` (or other broken CLI input that goes through parsec)
```
option -f: PoseidonPoseidonEntityParsingException "(line 1, column 2):\nunexpected \"<\""
```
Now:
```
option -f: Error when parsing the forge selection (either -f or --forgeFile):
unexpected "<"
```
And with --forgeFile, where the file contains only `<<>`
```
[Error]   Error when parsing the forge selection (either -f or --forgeFile):
unexpected "<"
```
***
YAML file with broken `orcid` field (or other yml fields)
```
[Warning] Could not parse YAML file 2010_RasmussenNature/POSEIDON.yml: AesonException "Error in $.contributor[0].orcid: (line 1, column 5):\nunexpected \".\""
```
```
[Warning] Could not parse YAML file 2010_RasmussenNature/POSEIDON.yml:
Aeson exception:
Error in $.contributor[0].orcid:
unexpected "."
```
With a broken date in `lastModified`:
```
[Warning] Could not parse YAML file /home/schmid/agora/community-archive/2010_RasmussenNature/POSEIDON.yml: AesonException "Error in $.lastModified: could not parse date: Failed reading: date must be of form [+,-]YYYY-MM-DD"
```
```
[Warning] Could not parse YAML file 2010_RasmussenNature/POSEIDON.yml:
Aeson exception:
Error in $.lastModified: could not parse date: Failed reading: date must be of form [+,-]YYYY-MM-DD
```

### CODE REVIEW

**Comment by nevrome** [comment]
I decided to use the opportunity to also suggest a solution for #244. I think the error shortening mechanism is only really relevant for the excessive `PoseidonGenotypeExceptionForward`. So I made it a feature of only this exception to include an `ErrorLength` to which its text should be truncated. This abolishes the general error truncation and makes it a much more specific feature.

Most importantly it now also covers warnings:

image

**Comment by stschiff** [comment]
Very nice, looking forward to it.

**Comment by nevrome** [comment]
I lost track of this PR. But it looks like the changes I applied so far are meaningful and complete. Maybe you could have a look, @stschiff. It's time for a Poseidon release with the amazing `--ordered` flag!

**Comment by stschiff** [comment]
Yes, true, will try to get this finished before I go on vacation, similarly to #304.

**Review by stschiff — APPROVED** [review]
Ok, looks great. Love the `showParsecErr` trick.

My own preference is not to make definitions like `data ErrorLength = CharInf | CharCount Int deriving Show` but instead use `Maybe Int` for this, but we had this discussion before, and I guess it comes down to personal coding style. My argument is that something like `CharInf`, while seemingly adding semantic interpretability, forces me to not only look up the function definitions where this is used, but also the definition. With `Nothing` on the other hand, I can just look up the function definition to understand its semantics. Anyway, totally fine like you have it now.

I have not tested this PR at all, and don't have time before vacation for this, so if you've tested things, then I certainly approve merging this in.

**Pull request merged**
