### PR TITLE
added simple 100-line running of genotype data.

### PR DESCRIPTION
**Pull request by stschiff**
Compiles, but not tested yet

### CODE REVIEW

**Comment by stschiff** [comment]
OK, this seems to do what we want. Have a look please. This is what I get when I run it on the faulty Saag et al dataset:
```
cloud@poseidonserver2:~/dev/poseidon-hs$ trident validate -d ~/poseidon-repos/published_data/2021_Saag_EastEuropean
Searching POSEIDON.yml files... 1 found
Initializing packages... 1 initialized
Packages loaded: 1
Checking first 100 SNPs of genotype data
Error in the genotype data: "EigenstratSnpEntry {snpChrom = 1, snpPos = 776546, snpGeneticPos = 2.0242e-2, snpId = \"rs12124819\", snpRef = 'N', snpAlt = 'A'}: encountered illegal genotype Hom-Ref with Ref-Allele missing"
```

**Comment by nevrome** [comment]
Alright - so I see two issues with this implementation:
- `validate` now fails without genotype data even with `--ignoreGeno`. We need it to run even without genotype data
- When validating a collection of packages the error message does not inform you in which one the error occurred

I think both of these issues could be solved by moving this check into `readPoseidonPackage` where all the other checks already live. There we already have the infrastructure to consider `--ignoreGeno` and are already working on the level of individual packages.

If you want to limit this check to `validate` then `readPoseidonPackage` and `readPoseidonPackageCollection` could get yet another flag for that. But it seems to be fast enough to run it also in `forge`, `genoconvert` and `fstats`.

**Comment by stschiff** [comment]
OK, agreed. But I don't think we need to run anything special in `fstats` or `genoconvert`, where this is automatically happening through the standard forge mechanism.

**Comment by nevrome** [comment]
Ah - ja - I get it. The question is though, if the pre-check would maybe yield a better error message even for `fstats` or `genoconvert`.

**Comment by stschiff** [comment]
OK done. Have a look.

**Comment by stschiff** [comment]
Ah sorry, haven't checked the tests. Just a sec.

**Comment by stschiff** [comment]
OK, great. From my end ready to merge.

**Pull request merged**
