### PR TITLE
Add CentOS built gh-action for conda deployment

### PR DESCRIPTION
**Pull request by stschiff**
Added a CentOS docker build workflow.

### CODE REVIEW

**Comment by stschiff** [comment]
@nevrome I don't know how to test workflows in non-master branches. Any clue?

**Comment by nevrome** [comment]
Feel free to test it on the master branch - it doesn't break anything and to be honest I do that all the time for changes to CI actions :slightly_smiling_face: You could theoretically also change when the action runs in the `on:` section, but I wouldn't go there.

Maybe we could call the produced executable trident-conda or something like this. Otherwise I fear CentOS users would be tempted to use it, and I think they should not, right? It's builds on an old version of CentOS only relevant for conda, correct?

**Comment by stschiff** [comment]
Right OK. Will merge. Hmm, it's CentOS7. And I agree it's misleading, because it makes no sense to call the other one `linux` then. Perhaps I'll call it `trident-conda-linux`.

**Comment by stschiff** [comment]
But how do I test it? Can I create a new tag which I'll remove after testing?

**Comment by nevrome** [comment]
Sure - just don't publish the release draft, if the build failed. You can delete a broken release draft and tag on github with the GUI and locally with `git tag -d v0.3.1`.

**Pull request merged**
