### PR TITLE
Fetch

### PR DESCRIPTION
**Pull request by nevrome**
#38

### CODE REVIEW

**Comment by stschiff** [comment]
Again impressive progress. Thanks. I'll checkout a local version and will have a look!

**Comment by nevrome** [comment]
It's not ready yet, but feel free to investigate. Updating packages where older versions are present is not really handled so far.

**Comment by nevrome** [comment]
So I think this generally works now. Needs testing and review :slightly_smiling_face:. Some open questions/ToDos:
- Right now only package names in the `forgeString` are considered, therefore the `forgeString` might not be the right choice here. Either this or we change the server code to also provide a list of individuals and groups.
- Related to that: The name `forgeString` is not really appropriate any more, now that we use it for both `forge` and `fetch`. If we keep the setup like this, then we should switch to a more generic name.
- I didn't write any user documentation for the README yet.

**Comment by nevrome** [comment]
One more thing: Fetch does not include an option to see the remote server content yet (e.g. `--preview`). I'm also not sure if this should go into fetch. Maybe it's better to introduce yet another module like `preview` or integrate the remote listing with `list`.

**Comment by stschiff** [comment]
OK, very impressive. Some comments/questions on the UI:
- I like the idea of putting the `--preview` functionality into `list`. It could be simply a `--remote` option in `list`, which would be a strict alternative to giving the base directories... you can either choose base directories or `--remote`.
- I think repurposing the forge-string is clever (apart from its name in the UI, indeed). How do you want the semantics to work here? When the user selects individuals or populations, I think ultimately we would still download the entire package, wouldn't we? We won't somehow try to download only those individuals, right?

I suggest you merge that PR in. I can't see any problems.

**Pull request merged**
