### PR TITLE
Added a newtype `JannoFile` for `[JannoRow]`

### PR DESCRIPTION
**Pull request by nevrome**
Here's an implementation of the idea shared in #229

### CODE REVIEW

**Review by stschiff — APPROVED** [review]
OK, I approve this. I think personally I would have not replaced all instances of `[JannoRow]` with `JannoFile`, in particular if the function just uses the rows directly, in which case I would have simply left things as they are. The monoid instance is useful, but only for merging Jannos, so it doesn't require making this change all the way through.

But I certainly don't mind how it is now, so this is good to merge.

**Comment by nevrome** [comment]
Right - my biggest concern is that `JannoFile` doesn't really capture the meaning. It's just an arbitrary list of `JannoRow`s. I considered naming it `JannoSet`, but a set has no order. `JannoList` is already in use. Do you have a suggestion?

I replaced all instances of `[JannoRow]` to make sure that it becomes harder to accidentally run into the issue I describe in #229. But I understand that it looks a bit weird at times, not least because of the type name.

**Comment by stschiff** [comment]
Yes, the name isn't perfect. You could have used `JannoMonoid`, but that's not a name you want everywhere. What about `JannoRows`?

**Comment by nevrome** [comment]
`JannoRows` is simple and clear. I love it. Will use that. Thanks!

**Pull request merged**
